### ISSUE TITLE
I can not open the file. How to fix the problem?

### ISSUE THREAD

**Issue by it19862** [zaagan/Docx-Html-Docx#1]
I can not open the file. How to fix the problem?

![0004](https://user-images.githubusercontent.com/18245828/40072911-04c6ccac-587e-11e8-898a-d9bd7adfa87e.gif)

**Comment by zaagan** [comment]
The issue was in the CKEditor plugin not being initialized properly on application start.

On a successful initialization, Your application had to look like this :

![image](https://user-images.githubusercontent.com/11134053/40107881-3293d1ca-5919-11e8-9f45-ea0a53433c61.png)

This issue has now been fixed. 👍  👍 👍 

Thank you
